// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  solderedDocsSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'General Information',
      // CH340 drivers
      // Soldered board dimensions (LEGO compatible)
      items: [
        {
          type: 'doc',
          id: 'misc/qwiic',
        },
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'category',
          label: '125KHZRFIDTAGREADER EDIT THIS NAME',
          items: [
            {
              type: 'doc',
              id: 'sensors/125khzrfidtagreader/125khzrfidtagreader-overview',
            },
            {
              type: 'doc',
              id: 'sensors/125khzrfidtagreader/125khzrfidtagreader-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/125khzrfidtagreader/125khzrfidtagreader-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/125khzrfidtagreader/arduino_library/125khzrfidtagreader-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/125khzrfidtagreader/arduino_library/125khzrfidtagreader-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/125khzrfidtagreader/arduino_library/125khzrfidtagreader-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'SLIDER-POTENTIOMETER',
          items: [
            {
              type: 'doc',
              id: 'sensors/slider-potentiometer/slider-potentiometer-overview',
            },
            {
              type: 'doc',
              id: 'sensors/slider-potentiometer/slider-potentiometer-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/slider-potentiometer/slider-potentiometer-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/slider-potentiometer/arduino_library/slider-potentiometer-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/slider-potentiometer/arduino_library/slider-potentiometer-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/slider-potentiometer/arduino_library/slider-potentiometer-arduino-3',
                },
              ],
            },
          ],
        },

        {
          type: 'category',
          label: 'Accelerometer & Gyroscope & Magnetometer LSM9DS1TR 9-DOF breakout',
          items: [
            {
              type: 'doc',
              id: 'sensors/lsm9ds1tr/lsm9ds1tr-overview',
            },
            {
              type: 'doc',
              id: 'sensors/lsm9ds1tr/lsm9ds1tr-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/lsm9ds1tr/lsm9ds1tr-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-init-config',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm9ds1tr/arduino_library/lsm9ds1tr-arduino-6',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Accelerometer & Gyroscope LSM6DS 6-DOF breakout',
          items: [
            {
              type: 'doc',
              id: 'sensors/lsm6ds3tr/lsm6ds3tr-overview',
            },
            {
              type: 'doc',
              id: 'sensors/lsm6ds3tr/lsm6ds3tr-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/lsm6ds3tr/lsm6ds3tr-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-6',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-4',
                },                {
                  type: 'doc',
                  id: 'sensors/lsm6ds3tr/arduino_library/lsm6ds3tr-arduino-5',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'ACCELEROMETER-GYROSCOPE EDIT THIS NAME',
          items: [
            {
              type: 'doc',
              id: 'sensors/accelerometer-gyroscope/accelerometer-gyroscope-overview',
            },
            {
              type: 'doc',
              id: 'sensors/accelerometer-gyroscope/accelerometer-gyroscope-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/accelerometer-gyroscope/accelerometer-gyroscope-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/accelerometer-gyroscope/arduino_library/accelerometer-gyroscope-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/accelerometer-gyroscope/arduino_library/accelerometer-gyroscope-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/accelerometer-gyroscope/arduino_library/accelerometer-gyroscope-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'SHTC3 Temperature and Humidity Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-overview',
            },
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-3',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Actuators',
      items: [
        {
          type: 'category',
          label: 'Basic Stepper Driver',
          items: [
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-overview',
            },
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-hardware',
            },
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-1'
                },
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-2'
                },
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-3'
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
